import { APPS, SMART_FOLDERS } from '@/data';

export interface SmartFolderResult {
  name: string;
  emoji: string;
  color: string;
  apps: string[];
}

export function buildSmartFolders(userApps: string[]): SmartFolderResult[] {
  const n = userApps.length;
  return SMART_FOLDERS.map((f) => {
    const myApps = n > 0
      ? userApps.filter((nm) => {
          const a = APPS.find((x) => x.n === nm);
          return a && (f.cats as readonly string[]).some((c) => a.c === c);
        })
      : APPS.filter((a) => (f.cats as readonly string[]).includes(a.c)).slice(0, 4).map((a) => a.n);
    return { name: f.n, emoji: f.e, color: f.col, apps: myApps };
  }).filter((f) => f.apps.length > 0 || n === 0);
}

export const DISTRACTION_LIST = [
  { n: 'TikTok', e: '🎵', r: 'Avg 2.4h/day', l: 'high' as const },
  { n: 'Instagram', e: '📸', r: 'Avg 1.8h/day', l: 'high' as const },
  { n: 'YouTube', e: '▶', r: 'Avg 2.0h/day', l: 'high' as const },
  { n: 'Twitter/X', e: '🐦', r: 'Avg 1.1h/day', l: 'medium' as const },
  { n: 'Reddit', e: '🤖', r: 'Avg 45min/day', l: 'medium' as const },
  { n: 'PUBG Mobile', e: '🎯', r: 'Multiple sessions', l: 'high' as const },
  { n: 'Free Fire', e: '🔥', r: 'Multiple sessions', l: 'high' as const },
];

export function buildMacDockGuide(folders: SmartFolderResult[], userApps: string[]): string {
  const lines = [
    'AuraCap — Mac Dock Layout Guide',
    '================================',
    '',
    'Follow these steps to organize your Mac Dock from your AuraCap smart folders.',
    '',
    'STEP 1 — Open System Settings',
    '  • Apple menu → System Settings → Desktop & Dock',
    '  • Scroll to "Dock" and set size / magnification to your taste',
    '',
    'STEP 2 — Remove clutter from the Dock',
    '  • Drag unused apps off the Dock until they poof away',
    '  • Keep Finder and Trash (system defaults)',
    '',
  ];

  const dockApps = folders.flatMap((f) => f.apps.slice(0, 2)).slice(0, 8);
  const extras = userApps.filter((a) => !dockApps.includes(a)).slice(0, 4);
  const finalDock = [...new Set([...dockApps, ...extras])].slice(0, 10);

  lines.push('STEP 3 — Add your priority apps (left to right)');
  finalDock.forEach((app, i) => {
    lines.push(`  ${i + 1}. Open Launchpad or Applications → drag "${app}" to the Dock`);
  });
  lines.push('');

  lines.push('STEP 4 — Group the rest in Launchpad folders');
  folders.forEach((f, i) => {
    lines.push(`  Folder ${i + 1}: "${f.name}" ${f.emoji}`);
    lines.push(`    Apps: ${f.apps.join(', ') || '(none yet — import apps in AuraCap)'}`);
    lines.push('    • Launchpad → drag one app onto another to create a folder');
    lines.push(`    • Name it "${f.name}" and add the apps listed above`);
    lines.push('');
  });

  lines.push('STEP 5 — Hide distraction apps from Dock');
  DISTRACTION_LIST.filter((d) => userApps.includes(d.n)).forEach((d) => {
    lines.push(`  • Remove "${d.n}" from Dock (${d.r}) — open via Spotlight when needed`);
  });
  if (!DISTRACTION_LIST.some((d) => userApps.includes(d.n))) {
    lines.push('  • No flagged distractions in your library — review Smart Organizer suggestions');
  }
  lines.push('');
  lines.push('STEP 6 — Optional: Hot Corners & Stage Manager');
  lines.push('  • System Settings → Desktop & Dock → Hot Corners → Mission Control');
  lines.push('  • Enable Stage Manager for focused single-app workflows');
  lines.push('');
  lines.push(`Generated by AuraCap · ${userApps.length} apps · ${folders.length} smart folders`);
  return lines.join('\n');
}

export function downloadMacDockGuide(folders: SmartFolderResult[], userApps: string[]) {
  const blob = new Blob([buildMacDockGuide(folders, userApps)], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'auracap-mac-dock-guide.txt';
  a.click();
  URL.revokeObjectURL(url);
}
